# Generated by Django 4.2.11 on 2026-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Canteen Staff'), ('DELIVERY', 'Delivery Personnel')], default='STUDENT', max_length=20),
        ),
    ]
