# Generated by Django 4.2.11 on 2026-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted'), ('banned', 'Banned'), ('held', 'Held'), ('penalized', 'Penalized')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
