# Generated by Django 5.1.5 on 2026-09-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
