# Generated by Django 4.2.11 on 2026-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0004_alter_category_id_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
