# Generated by Django 4.2.11 on 2026-08-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0005_menuitem_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='barcode',
        ),
    ]
