# Generated by Django 4.2.11 on 2026-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0006_remove_menuitem_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL galing sa internet', max_length=500, null=True),
        ),
    ]
