# Generated by Django 4.2.11 on 2026-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0007_menuitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=50, help_text='Available stock count'),
        ),
    ]
