# Generated by Django 6.1 on 2026-09-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0008_menuitem_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
