# Generated by Django 5.1.5 on 2026-09-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0009_alter_category_id_alter_menuitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
