# Generated by Django 5.1.5 on 2026-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0011_alter_category_id_alter_menuitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
