# Generated by Django 4.2.11 on 2026-08-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('biscuits', 'Biscuits'), ('rice', 'Rice Meals'), ('beverages', 'Beverages'), ('meryenda', 'Meryenda'), ('dietary', 'Dietary Plans')], default='rice', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, help_text='hal. Popular, Bestseller', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('image_url', models.URLField(blank=True, help_text='URL galing sa internet', max_length=500, null=True)),
                ('is_siomai', models.BooleanField(default=False, verbose_name='Is Siomai Customizer?')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available in Kiosk?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
