# Generated by Django 4.2.11 on 2026-09-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0005_order_delivery_fee_alter_menuitem_id_alter_order_id_and_more'),
    ]

    operations = [
    ]
