# Generated by Django 6.1 on 2026-09-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_merge_20260907_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('biscuits', 'Biscuits'), ('rice', 'Rice Meals'), ('beverages', 'Beverages'), ('meryenda', 'Meryenda'), ('dietary', 'Dietary Plans'), ('candies', 'Candies')], default='rice', max_length=20),
        ),
    ]
