# Generated by Django 5.1.5 on 2026-09-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0007_alter_menuitem_category'),
        ('customer_portal', '0008_alter_menuitem_id_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
    ]
