# Generated by Django 6.1 on 2026-09-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0010_order_delivery_fee_orderfeedback'),
    ]

    operations = [
    ]
