services:
  - type: web
    name: canteen-express
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate
    startCommand: gunicorn --chdir backend config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.hchqdkuijbpihraagetz
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
