# Generated by Django 6.0.7 on 2026-08-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(help_text='Building & Room Number', max_length=255)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching for Rider'), ('ACCEPTED', 'Rider Accepted'), ('REJECTED', 'Rejected'), ('TIMEOUT', 'No Rider Available (5-Min Timeout)')], default='SEARCHING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='order_management.order')),
                ('rider', models.ForeignKey(blank=True, limit_choices_to={'role': 'RIDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
