# Generated by Django 6.0.7 on 2026-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_deliveryrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
