# Generated by Django 4.2.11 on 2026-08-24 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0004_alter_deliveryrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Searching for Rider'), ('ACCEPTED', 'Rider Accepted'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected'), ('TIMEOUT', 'No Rider Available (5-Min Timeout)')], default='SEARCHING', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='deliveries.deliveryrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
