# Generated by Django 4.2.11 on 2026-08-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_alter_order_status'),
        ('deliveries', '0005_deliveryrequest_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='customer_portal.order'),
        ),
    ]
