# Generated by Django 6.1 on 2026-09-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_deliveryrequest_dest_lat_deliveryrequest_dest_lng_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymessage',
            options={'ordering': ['timestamp']},
        ),
    ]
