# Generated by Django 6.1 on 2026-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_deliveryrequest_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
