# Generated by Django 5.1.5 on 2026-09-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_alter_deliverymessage_id_alter_deliveryrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riderlocationpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
