# Generated by Django 6.1 on 2026-09-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_alter_deliverymessage_id_alter_deliveryrequest_id_and_more'),
    ]

    operations = [
    ]
