# Generated by Django 6.1 on 2026-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0015_deliveryrequest_dest_lat_deliveryrequest_dest_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
    ]
