# Generated by Django 5.1.5 on 2026-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_deliveryrequest_proof_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Searching for Rider'), ('ACCEPTED', 'Rider Accepted'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected'), ('TIMEOUT', 'No Rider Available (5-Min Timeout)')], db_index=True, default='SEARCHING', max_length=20),
        ),
    ]
