# Generated by Django 4.2.11 on 2026-08-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0003_alter_digitalqueueslip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalqueueslip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
