# Generated by Django 4.2.11 on 2026-08-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_alter_order_status'),
        ('queuing', '0004_alter_digitalqueueslip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalqueueslip',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_slip', to='customer_portal.order'),
        ),
    ]
