# Generated by Django 6.1 on 2026-09-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0005_alter_digitalqueueslip_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalqueueslip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
