# Generated by Django 5.1.5 on 2026-09-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0006_alter_digitalqueueslip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalqueueslip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
